server {
    listen 80;
    server_name https://srms.gi-kace.com.gh;

    # In production, you typically redirect HTTP -> HTTPS and terminate TLS
    # For local/staging, plain HTTP may be acceptable in a private network.

    location / {
        proxy_pass http://hris-portal:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
